[package]
name = "brickrust"
edition = "2021"

[features]
default=["brick_rigs_bricks_1_11"]
brick_rigs_bricks_1_11=[]
brick_rigs_1_11=["brick_rigs_bricks_1_11"]
process_internal_debug=[]

[workspace]
members = [ "macros", "brickworks", "xinput_proxy" ]

[dependencies]
bitflags= "2.13.1"
brickrust_macros = { path = "macros" }
brickworks = { path = "brickworks" }
xinput1_3 = { path = "xinput_proxy" }
min_hook_rs = "2.2.1"
iced-x86 = "1.21.0"
inventory = "0.3.24"
wchar = "0.11.1"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[example]]
name = "basic_init"
crate-type = ["dylib"]

[[example]]
name = "custom_brick_properties"
crate-type = ["dylib"]

[[example]]
name = "workshop_allow_modded"
crate-type = ["dylib"]

[[example]]
name = "function_tests"
crate-type = ["dylib"]
