[package]
name = "brickrust"
edition = "2021"

[[example]]
name = "basic_init"
crate-type = ["dylib"]

[[example]]
name = "custom_brick_properties"
crate-type = ["dylib"]

[features]
default=["brick_rigs_bricks_1_11_0"]
brick_rigs_bricks_1_11_0=[]
brick_rigs_1_11_0=["brick_rigs_bricks_1_11_0"]

[workspace]
members = [ "macros", "brickworks", "xinput_proxy"]

[dependencies]
bitflags= "2.13.1"
brickrust_macros = { path = "macros" }
brickworks = { path = "brickworks" }
xinput1_3 = { path = "xinput_proxy" }
min_hook_rs = "2.2.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
