/* automatically generated by rust-bindgen 0.72.1 */
#![allow(nonstandard_style)]
pub mod backend;

pub const MU_VERSION: &[u8; 5] = b"2.02\0";
pub const MU_COMMANDLIST_SIZE: u32 = 262144;
pub const MU_ROOTLIST_SIZE: u32 = 32;
pub const MU_CONTAINERSTACK_SIZE: u32 = 32;
pub const MU_CLIPSTACK_SIZE: u32 = 32;
pub const MU_IDSTACK_SIZE: u32 = 32;
pub const MU_LAYOUTSTACK_SIZE: u32 = 16;
pub const MU_CONTAINERPOOL_SIZE: u32 = 48;
pub const MU_TREENODEPOOL_SIZE: u32 = 48;
pub const MU_MAX_WIDTHS: u32 = 16;
pub const MU_REAL_FMT: &[u8; 5] = b"%.3g\0";
pub const MU_SLIDER_FMT: &[u8; 5] = b"%.2f\0";
pub const MU_MAX_FMT: u32 = 127;
pub const MU_CLIP_PART: _bindgen_ty_1 = 1;
pub const MU_CLIP_ALL: _bindgen_ty_1 = 2;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub const MU_COMMAND_JUMP: _bindgen_ty_2 = 1;
pub const MU_COMMAND_CLIP: _bindgen_ty_2 = 2;
pub const MU_COMMAND_RECT: _bindgen_ty_2 = 3;
pub const MU_COMMAND_TEXT: _bindgen_ty_2 = 4;
pub const MU_COMMAND_ICON: _bindgen_ty_2 = 5;
pub const MU_COMMAND_MAX: _bindgen_ty_2 = 6;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
pub const MU_COLOR_TEXT: _bindgen_ty_3 = 0;
pub const MU_COLOR_BORDER: _bindgen_ty_3 = 1;
pub const MU_COLOR_WINDOWBG: _bindgen_ty_3 = 2;
pub const MU_COLOR_TITLEBG: _bindgen_ty_3 = 3;
pub const MU_COLOR_TITLETEXT: _bindgen_ty_3 = 4;
pub const MU_COLOR_PANELBG: _bindgen_ty_3 = 5;
pub const MU_COLOR_BUTTON: _bindgen_ty_3 = 6;
pub const MU_COLOR_BUTTONHOVER: _bindgen_ty_3 = 7;
pub const MU_COLOR_BUTTONFOCUS: _bindgen_ty_3 = 8;
pub const MU_COLOR_BASE: _bindgen_ty_3 = 9;
pub const MU_COLOR_BASEHOVER: _bindgen_ty_3 = 10;
pub const MU_COLOR_BASEFOCUS: _bindgen_ty_3 = 11;
pub const MU_COLOR_SCROLLBASE: _bindgen_ty_3 = 12;
pub const MU_COLOR_SCROLLTHUMB: _bindgen_ty_3 = 13;
pub const MU_COLOR_MAX: _bindgen_ty_3 = 14;
pub type _bindgen_ty_3 = ::std::os::raw::c_uint;
pub const MU_ICON_CLOSE: _bindgen_ty_4 = 1;
pub const MU_ICON_CHECK: _bindgen_ty_4 = 2;
pub const MU_ICON_COLLAPSED: _bindgen_ty_4 = 3;
pub const MU_ICON_EXPANDED: _bindgen_ty_4 = 4;
pub const MU_ICON_MAX: _bindgen_ty_4 = 5;
pub type _bindgen_ty_4 = ::std::os::raw::c_uint;
pub const MU_RES_ACTIVE: _bindgen_ty_5 = 1;
pub const MU_RES_SUBMIT: _bindgen_ty_5 = 2;
pub const MU_RES_CHANGE: _bindgen_ty_5 = 4;
pub type _bindgen_ty_5 = ::std::os::raw::c_uint;
pub const MU_OPT_ALIGNCENTER: _bindgen_ty_6 = 1;
pub const MU_OPT_ALIGNRIGHT: _bindgen_ty_6 = 2;
pub const MU_OPT_NOINTERACT: _bindgen_ty_6 = 4;
pub const MU_OPT_NOFRAME: _bindgen_ty_6 = 8;
pub const MU_OPT_NORESIZE: _bindgen_ty_6 = 16;
pub const MU_OPT_NOSCROLL: _bindgen_ty_6 = 32;
pub const MU_OPT_NOCLOSE: _bindgen_ty_6 = 64;
pub const MU_OPT_NOTITLE: _bindgen_ty_6 = 128;
pub const MU_OPT_HOLDFOCUS: _bindgen_ty_6 = 256;
pub const MU_OPT_AUTOSIZE: _bindgen_ty_6 = 512;
pub const MU_OPT_POPUP: _bindgen_ty_6 = 1024;
pub const MU_OPT_CLOSED: _bindgen_ty_6 = 2048;
pub const MU_OPT_EXPANDED: _bindgen_ty_6 = 4096;
pub type _bindgen_ty_6 = ::std::os::raw::c_uint;
pub const MU_MOUSE_LEFT: _bindgen_ty_7 = 1;
pub const MU_MOUSE_RIGHT: _bindgen_ty_7 = 2;
pub const MU_MOUSE_MIDDLE: _bindgen_ty_7 = 4;
pub type _bindgen_ty_7 = ::std::os::raw::c_uint;
pub const MU_KEY_SHIFT: _bindgen_ty_8 = 1;
pub const MU_KEY_CTRL: _bindgen_ty_8 = 2;
pub const MU_KEY_ALT: _bindgen_ty_8 = 4;
pub const MU_KEY_BACKSPACE: _bindgen_ty_8 = 8;
pub const MU_KEY_RETURN: _bindgen_ty_8 = 16;
pub type _bindgen_ty_8 = ::std::os::raw::c_uint;
pub type mu_Id = ::std::os::raw::c_uint;
pub type mu_Real = f32;
pub type mu_Font = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Vec2 {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Vec2"][::std::mem::size_of::<mu_Vec2>() - 8usize];
    ["Alignment of mu_Vec2"][::std::mem::align_of::<mu_Vec2>() - 4usize];
    ["Offset of field: mu_Vec2::x"][::std::mem::offset_of!(mu_Vec2, x) - 0usize];
    ["Offset of field: mu_Vec2::y"][::std::mem::offset_of!(mu_Vec2, y) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Rect {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
    pub w: ::std::os::raw::c_int,
    pub h: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Rect"][::std::mem::size_of::<mu_Rect>() - 16usize];
    ["Alignment of mu_Rect"][::std::mem::align_of::<mu_Rect>() - 4usize];
    ["Offset of field: mu_Rect::x"][::std::mem::offset_of!(mu_Rect, x) - 0usize];
    ["Offset of field: mu_Rect::y"][::std::mem::offset_of!(mu_Rect, y) - 4usize];
    ["Offset of field: mu_Rect::w"][::std::mem::offset_of!(mu_Rect, w) - 8usize];
    ["Offset of field: mu_Rect::h"][::std::mem::offset_of!(mu_Rect, h) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Color {
    pub r: ::std::os::raw::c_uchar,
    pub g: ::std::os::raw::c_uchar,
    pub b: ::std::os::raw::c_uchar,
    pub a: ::std::os::raw::c_uchar,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Color"][::std::mem::size_of::<mu_Color>() - 4usize];
    ["Alignment of mu_Color"][::std::mem::align_of::<mu_Color>() - 1usize];
    ["Offset of field: mu_Color::r"][::std::mem::offset_of!(mu_Color, r) - 0usize];
    ["Offset of field: mu_Color::g"][::std::mem::offset_of!(mu_Color, g) - 1usize];
    ["Offset of field: mu_Color::b"][::std::mem::offset_of!(mu_Color, b) - 2usize];
    ["Offset of field: mu_Color::a"][::std::mem::offset_of!(mu_Color, a) - 3usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_PoolItem {
    pub id: mu_Id,
    pub last_update: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_PoolItem"][::std::mem::size_of::<mu_PoolItem>() - 8usize];
    ["Alignment of mu_PoolItem"][::std::mem::align_of::<mu_PoolItem>() - 4usize];
    ["Offset of field: mu_PoolItem::id"][::std::mem::offset_of!(mu_PoolItem, id) - 0usize];
    ["Offset of field: mu_PoolItem::last_update"]
        [::std::mem::offset_of!(mu_PoolItem, last_update) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_BaseCommand {
    pub type_: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_BaseCommand"][::std::mem::size_of::<mu_BaseCommand>() - 8usize];
    ["Alignment of mu_BaseCommand"][::std::mem::align_of::<mu_BaseCommand>() - 4usize];
    ["Offset of field: mu_BaseCommand::type_"]
        [::std::mem::offset_of!(mu_BaseCommand, type_) - 0usize];
    ["Offset of field: mu_BaseCommand::size"]
        [::std::mem::offset_of!(mu_BaseCommand, size) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_JumpCommand {
    pub base: mu_BaseCommand,
    pub dst: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_JumpCommand"][::std::mem::size_of::<mu_JumpCommand>() - 16usize];
    ["Alignment of mu_JumpCommand"][::std::mem::align_of::<mu_JumpCommand>() - 8usize];
    ["Offset of field: mu_JumpCommand::base"]
        [::std::mem::offset_of!(mu_JumpCommand, base) - 0usize];
    ["Offset of field: mu_JumpCommand::dst"][::std::mem::offset_of!(mu_JumpCommand, dst) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_ClipCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_ClipCommand"][::std::mem::size_of::<mu_ClipCommand>() - 24usize];
    ["Alignment of mu_ClipCommand"][::std::mem::align_of::<mu_ClipCommand>() - 4usize];
    ["Offset of field: mu_ClipCommand::base"]
        [::std::mem::offset_of!(mu_ClipCommand, base) - 0usize];
    ["Offset of field: mu_ClipCommand::rect"]
        [::std::mem::offset_of!(mu_ClipCommand, rect) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_RectCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
    pub color: mu_Color,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_RectCommand"][::std::mem::size_of::<mu_RectCommand>() - 28usize];
    ["Alignment of mu_RectCommand"][::std::mem::align_of::<mu_RectCommand>() - 4usize];
    ["Offset of field: mu_RectCommand::base"]
        [::std::mem::offset_of!(mu_RectCommand, base) - 0usize];
    ["Offset of field: mu_RectCommand::rect"]
        [::std::mem::offset_of!(mu_RectCommand, rect) - 8usize];
    ["Offset of field: mu_RectCommand::color"]
        [::std::mem::offset_of!(mu_RectCommand, color) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_TextCommand {
    pub base: mu_BaseCommand,
    pub font: mu_Font,
    pub pos: mu_Vec2,
    pub color: mu_Color,
    pub str_: [::std::os::raw::c_char; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_TextCommand"][::std::mem::size_of::<mu_TextCommand>() - 32usize];
    ["Alignment of mu_TextCommand"][::std::mem::align_of::<mu_TextCommand>() - 8usize];
    ["Offset of field: mu_TextCommand::base"]
        [::std::mem::offset_of!(mu_TextCommand, base) - 0usize];
    ["Offset of field: mu_TextCommand::font"]
        [::std::mem::offset_of!(mu_TextCommand, font) - 8usize];
    ["Offset of field: mu_TextCommand::pos"][::std::mem::offset_of!(mu_TextCommand, pos) - 16usize];
    ["Offset of field: mu_TextCommand::color"]
        [::std::mem::offset_of!(mu_TextCommand, color) - 24usize];
    ["Offset of field: mu_TextCommand::str_"]
        [::std::mem::offset_of!(mu_TextCommand, str_) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_IconCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
    pub id: ::std::os::raw::c_int,
    pub color: mu_Color,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_IconCommand"][::std::mem::size_of::<mu_IconCommand>() - 32usize];
    ["Alignment of mu_IconCommand"][::std::mem::align_of::<mu_IconCommand>() - 4usize];
    ["Offset of field: mu_IconCommand::base"]
        [::std::mem::offset_of!(mu_IconCommand, base) - 0usize];
    ["Offset of field: mu_IconCommand::rect"]
        [::std::mem::offset_of!(mu_IconCommand, rect) - 8usize];
    ["Offset of field: mu_IconCommand::id"][::std::mem::offset_of!(mu_IconCommand, id) - 24usize];
    ["Offset of field: mu_IconCommand::color"]
        [::std::mem::offset_of!(mu_IconCommand, color) - 28usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mu_Command {
    pub type_: ::std::os::raw::c_int,
    pub base: mu_BaseCommand,
    pub jump: mu_JumpCommand,
    pub clip: mu_ClipCommand,
    pub rect: mu_RectCommand,
    pub text: mu_TextCommand,
    pub icon: mu_IconCommand,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Command"][::std::mem::size_of::<mu_Command>() - 32usize];
    ["Alignment of mu_Command"][::std::mem::align_of::<mu_Command>() - 8usize];
    ["Offset of field: mu_Command::type_"][::std::mem::offset_of!(mu_Command, type_) - 0usize];
    ["Offset of field: mu_Command::base"][::std::mem::offset_of!(mu_Command, base) - 0usize];
    ["Offset of field: mu_Command::jump"][::std::mem::offset_of!(mu_Command, jump) - 0usize];
    ["Offset of field: mu_Command::clip"][::std::mem::offset_of!(mu_Command, clip) - 0usize];
    ["Offset of field: mu_Command::rect"][::std::mem::offset_of!(mu_Command, rect) - 0usize];
    ["Offset of field: mu_Command::text"][::std::mem::offset_of!(mu_Command, text) - 0usize];
    ["Offset of field: mu_Command::icon"][::std::mem::offset_of!(mu_Command, icon) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Layout {
    pub body: mu_Rect,
    pub next: mu_Rect,
    pub position: mu_Vec2,
    pub size: mu_Vec2,
    pub max: mu_Vec2,
    pub widths: [::std::os::raw::c_int; 16usize],
    pub items: ::std::os::raw::c_int,
    pub item_index: ::std::os::raw::c_int,
    pub next_row: ::std::os::raw::c_int,
    pub next_type: ::std::os::raw::c_int,
    pub indent: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Layout"][::std::mem::size_of::<mu_Layout>() - 140usize];
    ["Alignment of mu_Layout"][::std::mem::align_of::<mu_Layout>() - 4usize];
    ["Offset of field: mu_Layout::body"][::std::mem::offset_of!(mu_Layout, body) - 0usize];
    ["Offset of field: mu_Layout::next"][::std::mem::offset_of!(mu_Layout, next) - 16usize];
    ["Offset of field: mu_Layout::position"][::std::mem::offset_of!(mu_Layout, position) - 32usize];
    ["Offset of field: mu_Layout::size"][::std::mem::offset_of!(mu_Layout, size) - 40usize];
    ["Offset of field: mu_Layout::max"][::std::mem::offset_of!(mu_Layout, max) - 48usize];
    ["Offset of field: mu_Layout::widths"][::std::mem::offset_of!(mu_Layout, widths) - 56usize];
    ["Offset of field: mu_Layout::items"][::std::mem::offset_of!(mu_Layout, items) - 120usize];
    ["Offset of field: mu_Layout::item_index"]
        [::std::mem::offset_of!(mu_Layout, item_index) - 124usize];
    ["Offset of field: mu_Layout::next_row"]
        [::std::mem::offset_of!(mu_Layout, next_row) - 128usize];
    ["Offset of field: mu_Layout::next_type"]
        [::std::mem::offset_of!(mu_Layout, next_type) - 132usize];
    ["Offset of field: mu_Layout::indent"][::std::mem::offset_of!(mu_Layout, indent) - 136usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Container {
    pub head: *mut mu_Command,
    pub tail: *mut mu_Command,
    pub rect: mu_Rect,
    pub body: mu_Rect,
    pub content_size: mu_Vec2,
    pub scroll: mu_Vec2,
    pub zindex: ::std::os::raw::c_int,
    pub open: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Container"][::std::mem::size_of::<mu_Container>() - 72usize];
    ["Alignment of mu_Container"][::std::mem::align_of::<mu_Container>() - 8usize];
    ["Offset of field: mu_Container::head"][::std::mem::offset_of!(mu_Container, head) - 0usize];
    ["Offset of field: mu_Container::tail"][::std::mem::offset_of!(mu_Container, tail) - 8usize];
    ["Offset of field: mu_Container::rect"][::std::mem::offset_of!(mu_Container, rect) - 16usize];
    ["Offset of field: mu_Container::body"][::std::mem::offset_of!(mu_Container, body) - 32usize];
    ["Offset of field: mu_Container::content_size"]
        [::std::mem::offset_of!(mu_Container, content_size) - 48usize];
    ["Offset of field: mu_Container::scroll"]
        [::std::mem::offset_of!(mu_Container, scroll) - 56usize];
    ["Offset of field: mu_Container::zindex"]
        [::std::mem::offset_of!(mu_Container, zindex) - 64usize];
    ["Offset of field: mu_Container::open"][::std::mem::offset_of!(mu_Container, open) - 68usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Style {
    pub font: mu_Font,
    pub size: mu_Vec2,
    pub padding: ::std::os::raw::c_int,
    pub spacing: ::std::os::raw::c_int,
    pub indent: ::std::os::raw::c_int,
    pub title_height: ::std::os::raw::c_int,
    pub scrollbar_size: ::std::os::raw::c_int,
    pub thumb_size: ::std::os::raw::c_int,
    pub colors: [mu_Color; 14usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Style"][::std::mem::size_of::<mu_Style>() - 96usize];
    ["Alignment of mu_Style"][::std::mem::align_of::<mu_Style>() - 8usize];
    ["Offset of field: mu_Style::font"][::std::mem::offset_of!(mu_Style, font) - 0usize];
    ["Offset of field: mu_Style::size"][::std::mem::offset_of!(mu_Style, size) - 8usize];
    ["Offset of field: mu_Style::padding"][::std::mem::offset_of!(mu_Style, padding) - 16usize];
    ["Offset of field: mu_Style::spacing"][::std::mem::offset_of!(mu_Style, spacing) - 20usize];
    ["Offset of field: mu_Style::indent"][::std::mem::offset_of!(mu_Style, indent) - 24usize];
    ["Offset of field: mu_Style::title_height"]
        [::std::mem::offset_of!(mu_Style, title_height) - 28usize];
    ["Offset of field: mu_Style::scrollbar_size"]
        [::std::mem::offset_of!(mu_Style, scrollbar_size) - 32usize];
    ["Offset of field: mu_Style::thumb_size"]
        [::std::mem::offset_of!(mu_Style, thumb_size) - 36usize];
    ["Offset of field: mu_Style::colors"][::std::mem::offset_of!(mu_Style, colors) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context {
    pub text_width: ::std::option::Option<
        unsafe extern "C" fn(
            font: mu_Font,
            str_: *const ::std::os::raw::c_char,
            len: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub text_height:
        ::std::option::Option<unsafe extern "C" fn(font: mu_Font) -> ::std::os::raw::c_int>,
    pub draw_frame: ::std::option::Option<
        unsafe extern "C" fn(ctx: *mut mu_Context, rect: mu_Rect, colorid: ::std::os::raw::c_int),
    >,
    pub _style: mu_Style,
    pub style: *mut mu_Style,
    pub hover: mu_Id,
    pub focus: mu_Id,
    pub last_id: mu_Id,
    pub last_rect: mu_Rect,
    pub last_zindex: ::std::os::raw::c_int,
    pub updated_focus: ::std::os::raw::c_int,
    pub frame: ::std::os::raw::c_int,
    pub hover_root: *mut mu_Container,
    pub next_hover_root: *mut mu_Container,
    pub scroll_target: *mut mu_Container,
    pub number_edit_buf: [::std::os::raw::c_char; 127usize],
    pub number_edit: mu_Id,
    pub command_list: mu_Context__bindgen_ty_1,
    pub root_list: mu_Context__bindgen_ty_2,
    pub container_stack: mu_Context__bindgen_ty_3,
    pub clip_stack: mu_Context__bindgen_ty_4,
    pub id_stack: mu_Context__bindgen_ty_5,
    pub layout_stack: mu_Context__bindgen_ty_6,
    pub container_pool: [mu_PoolItem; 48usize],
    pub containers: [mu_Container; 48usize],
    pub treenode_pool: [mu_PoolItem; 48usize],
    pub mouse_pos: mu_Vec2,
    pub last_mouse_pos: mu_Vec2,
    pub mouse_delta: mu_Vec2,
    pub scroll_delta: mu_Vec2,
    pub mouse_down: ::std::os::raw::c_int,
    pub mouse_pressed: ::std::os::raw::c_int,
    pub key_down: ::std::os::raw::c_int,
    pub key_pressed: ::std::os::raw::c_int,
    pub input_text: [::std::os::raw::c_char; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_1 {
    pub idx: ::std::os::raw::c_int,
    pub items: [::std::os::raw::c_char; 262144usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_1"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_1>() - 262148usize];
    ["Alignment of mu_Context__bindgen_ty_1"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_1>() - 4usize];
    ["Offset of field: mu_Context__bindgen_ty_1::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_1, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_1::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_1, items) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_2 {
    pub idx: ::std::os::raw::c_int,
    pub items: [*mut mu_Container; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_2"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_2>() - 264usize];
    ["Alignment of mu_Context__bindgen_ty_2"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_2>() - 8usize];
    ["Offset of field: mu_Context__bindgen_ty_2::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_2, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_2::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_2, items) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_3 {
    pub idx: ::std::os::raw::c_int,
    pub items: [*mut mu_Container; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_3"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_3>() - 264usize];
    ["Alignment of mu_Context__bindgen_ty_3"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_3>() - 8usize];
    ["Offset of field: mu_Context__bindgen_ty_3::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_3, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_3::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_3, items) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_4 {
    pub idx: ::std::os::raw::c_int,
    pub items: [mu_Rect; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_4"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_4>() - 516usize];
    ["Alignment of mu_Context__bindgen_ty_4"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_4>() - 4usize];
    ["Offset of field: mu_Context__bindgen_ty_4::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_4, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_4::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_4, items) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_5 {
    pub idx: ::std::os::raw::c_int,
    pub items: [mu_Id; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_5"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_5>() - 132usize];
    ["Alignment of mu_Context__bindgen_ty_5"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_5>() - 4usize];
    ["Offset of field: mu_Context__bindgen_ty_5::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_5, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_5::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_5, items) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_6 {
    pub idx: ::std::os::raw::c_int,
    pub items: [mu_Layout; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context__bindgen_ty_6"]
        [::std::mem::size_of::<mu_Context__bindgen_ty_6>() - 2244usize];
    ["Alignment of mu_Context__bindgen_ty_6"]
        [::std::mem::align_of::<mu_Context__bindgen_ty_6>() - 4usize];
    ["Offset of field: mu_Context__bindgen_ty_6::idx"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_6, idx) - 0usize];
    ["Offset of field: mu_Context__bindgen_ty_6::items"]
        [::std::mem::offset_of!(mu_Context__bindgen_ty_6, items) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mu_Context"][::std::mem::size_of::<mu_Context>() - 270200usize];
    ["Alignment of mu_Context"][::std::mem::align_of::<mu_Context>() - 8usize];
    ["Offset of field: mu_Context::text_width"]
        [::std::mem::offset_of!(mu_Context, text_width) - 0usize];
    ["Offset of field: mu_Context::text_height"]
        [::std::mem::offset_of!(mu_Context, text_height) - 8usize];
    ["Offset of field: mu_Context::draw_frame"]
        [::std::mem::offset_of!(mu_Context, draw_frame) - 16usize];
    ["Offset of field: mu_Context::_style"][::std::mem::offset_of!(mu_Context, _style) - 24usize];
    ["Offset of field: mu_Context::style"][::std::mem::offset_of!(mu_Context, style) - 120usize];
    ["Offset of field: mu_Context::hover"][::std::mem::offset_of!(mu_Context, hover) - 128usize];
    ["Offset of field: mu_Context::focus"][::std::mem::offset_of!(mu_Context, focus) - 132usize];
    ["Offset of field: mu_Context::last_id"]
        [::std::mem::offset_of!(mu_Context, last_id) - 136usize];
    ["Offset of field: mu_Context::last_rect"]
        [::std::mem::offset_of!(mu_Context, last_rect) - 140usize];
    ["Offset of field: mu_Context::last_zindex"]
        [::std::mem::offset_of!(mu_Context, last_zindex) - 156usize];
    ["Offset of field: mu_Context::updated_focus"]
        [::std::mem::offset_of!(mu_Context, updated_focus) - 160usize];
    ["Offset of field: mu_Context::frame"][::std::mem::offset_of!(mu_Context, frame) - 164usize];
    ["Offset of field: mu_Context::hover_root"]
        [::std::mem::offset_of!(mu_Context, hover_root) - 168usize];
    ["Offset of field: mu_Context::next_hover_root"]
        [::std::mem::offset_of!(mu_Context, next_hover_root) - 176usize];
    ["Offset of field: mu_Context::scroll_target"]
        [::std::mem::offset_of!(mu_Context, scroll_target) - 184usize];
    ["Offset of field: mu_Context::number_edit_buf"]
        [::std::mem::offset_of!(mu_Context, number_edit_buf) - 192usize];
    ["Offset of field: mu_Context::number_edit"]
        [::std::mem::offset_of!(mu_Context, number_edit) - 320usize];
    ["Offset of field: mu_Context::command_list"]
        [::std::mem::offset_of!(mu_Context, command_list) - 324usize];
    ["Offset of field: mu_Context::root_list"]
        [::std::mem::offset_of!(mu_Context, root_list) - 262472usize];
    ["Offset of field: mu_Context::container_stack"]
        [::std::mem::offset_of!(mu_Context, container_stack) - 262736usize];
    ["Offset of field: mu_Context::clip_stack"]
        [::std::mem::offset_of!(mu_Context, clip_stack) - 263000usize];
    ["Offset of field: mu_Context::id_stack"]
        [::std::mem::offset_of!(mu_Context, id_stack) - 263516usize];
    ["Offset of field: mu_Context::layout_stack"]
        [::std::mem::offset_of!(mu_Context, layout_stack) - 263648usize];
    ["Offset of field: mu_Context::container_pool"]
        [::std::mem::offset_of!(mu_Context, container_pool) - 265892usize];
    ["Offset of field: mu_Context::containers"]
        [::std::mem::offset_of!(mu_Context, containers) - 266280usize];
    ["Offset of field: mu_Context::treenode_pool"]
        [::std::mem::offset_of!(mu_Context, treenode_pool) - 269736usize];
    ["Offset of field: mu_Context::mouse_pos"]
        [::std::mem::offset_of!(mu_Context, mouse_pos) - 270120usize];
    ["Offset of field: mu_Context::last_mouse_pos"]
        [::std::mem::offset_of!(mu_Context, last_mouse_pos) - 270128usize];
    ["Offset of field: mu_Context::mouse_delta"]
        [::std::mem::offset_of!(mu_Context, mouse_delta) - 270136usize];
    ["Offset of field: mu_Context::scroll_delta"]
        [::std::mem::offset_of!(mu_Context, scroll_delta) - 270144usize];
    ["Offset of field: mu_Context::mouse_down"]
        [::std::mem::offset_of!(mu_Context, mouse_down) - 270152usize];
    ["Offset of field: mu_Context::mouse_pressed"]
        [::std::mem::offset_of!(mu_Context, mouse_pressed) - 270156usize];
    ["Offset of field: mu_Context::key_down"]
        [::std::mem::offset_of!(mu_Context, key_down) - 270160usize];
    ["Offset of field: mu_Context::key_pressed"]
        [::std::mem::offset_of!(mu_Context, key_pressed) - 270164usize];
    ["Offset of field: mu_Context::input_text"]
        [::std::mem::offset_of!(mu_Context, input_text) - 270168usize];
};
unsafe extern "C" {
    pub fn mu_vec2(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int) -> mu_Vec2;
}
unsafe extern "C" {
    pub fn mu_rect(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        w: ::std::os::raw::c_int,
        h: ::std::os::raw::c_int,
    ) -> mu_Rect;
}
unsafe extern "C" {
    pub fn mu_color(
        r: ::std::os::raw::c_int,
        g: ::std::os::raw::c_int,
        b: ::std::os::raw::c_int,
        a: ::std::os::raw::c_int,
    ) -> mu_Color;
}
unsafe extern "C" {
    pub fn mu_init(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_begin(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_end(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_set_focus(ctx: *mut mu_Context, id: mu_Id);
}
unsafe extern "C" {
    pub fn mu_get_id(
        ctx: *mut mu_Context,
        data: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
    ) -> mu_Id;
}
unsafe extern "C" {
    pub fn mu_push_id(
        ctx: *mut mu_Context,
        data: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_pop_id(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_push_clip_rect(ctx: *mut mu_Context, rect: mu_Rect);
}
unsafe extern "C" {
    pub fn mu_pop_clip_rect(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_get_clip_rect(ctx: *mut mu_Context) -> mu_Rect;
}
unsafe extern "C" {
    pub fn mu_check_clip(ctx: *mut mu_Context, r: mu_Rect) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_get_current_container(ctx: *mut mu_Context) -> *mut mu_Container;
}
unsafe extern "C" {
    pub fn mu_get_container(
        ctx: *mut mu_Context,
        name: *const ::std::os::raw::c_char,
    ) -> *mut mu_Container;
}
unsafe extern "C" {
    pub fn mu_bring_to_front(ctx: *mut mu_Context, cnt: *mut mu_Container);
}
unsafe extern "C" {
    pub fn mu_pool_init(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        len: ::std::os::raw::c_int,
        id: mu_Id,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_pool_get(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        len: ::std::os::raw::c_int,
        id: mu_Id,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_pool_update(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        idx: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_input_mousemove(
        ctx: *mut mu_Context,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_input_mousedown(
        ctx: *mut mu_Context,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        btn: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_input_mouseup(
        ctx: *mut mu_Context,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        btn: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_input_scroll(
        ctx: *mut mu_Context,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_input_keydown(ctx: *mut mu_Context, key: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mu_input_keyup(ctx: *mut mu_Context, key: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mu_input_text(ctx: *mut mu_Context, text: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn mu_push_command(
        ctx: *mut mu_Context,
        type_: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
    ) -> *mut mu_Command;
}
unsafe extern "C" {
    pub fn mu_next_command(
        ctx: *mut mu_Context,
        cmd: *mut *mut mu_Command,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_set_clip(ctx: *mut mu_Context, rect: mu_Rect);
}
unsafe extern "C" {
    pub fn mu_draw_rect(ctx: *mut mu_Context, rect: mu_Rect, color: mu_Color);
}
unsafe extern "C" {
    pub fn mu_draw_box(ctx: *mut mu_Context, rect: mu_Rect, color: mu_Color);
}
unsafe extern "C" {
    pub fn mu_draw_text(
        ctx: *mut mu_Context,
        font: mu_Font,
        str_: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        pos: mu_Vec2,
        color: mu_Color,
    );
}
unsafe extern "C" {
    pub fn mu_draw_icon(
        ctx: *mut mu_Context,
        id: ::std::os::raw::c_int,
        rect: mu_Rect,
        color: mu_Color,
    );
}
unsafe extern "C" {
    pub fn mu_layout_row(
        ctx: *mut mu_Context,
        items: ::std::os::raw::c_int,
        widths: *const ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_layout_width(ctx: *mut mu_Context, width: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mu_layout_height(ctx: *mut mu_Context, height: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mu_layout_begin_column(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_layout_end_column(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_layout_set_next(ctx: *mut mu_Context, r: mu_Rect, relative: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mu_layout_next(ctx: *mut mu_Context) -> mu_Rect;
}
unsafe extern "C" {
    pub fn mu_draw_control_frame(
        ctx: *mut mu_Context,
        id: mu_Id,
        rect: mu_Rect,
        colorid: ::std::os::raw::c_int,
        opt: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_draw_control_text(
        ctx: *mut mu_Context,
        str_: *const ::std::os::raw::c_char,
        rect: mu_Rect,
        colorid: ::std::os::raw::c_int,
        opt: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_mouse_over(ctx: *mut mu_Context, rect: mu_Rect) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_update_control(
        ctx: *mut mu_Context,
        id: mu_Id,
        rect: mu_Rect,
        opt: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_text(ctx: *mut mu_Context, text: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn mu_label(ctx: *mut mu_Context, text: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn mu_button_ex(
        ctx: *mut mu_Context,
        label: *const ::std::os::raw::c_char,
        icon: ::std::os::raw::c_int,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_checkbox(
        ctx: *mut mu_Context,
        label: *const ::std::os::raw::c_char,
        state: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_textbox_raw(
        ctx: *mut mu_Context,
        buf: *mut ::std::os::raw::c_char,
        bufsz: ::std::os::raw::c_int,
        id: mu_Id,
        r: mu_Rect,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_textbox_ex(
        ctx: *mut mu_Context,
        buf: *mut ::std::os::raw::c_char,
        bufsz: ::std::os::raw::c_int,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_slider_ex(
        ctx: *mut mu_Context,
        value: *mut mu_Real,
        low: mu_Real,
        high: mu_Real,
        step: mu_Real,
        fmt: *const ::std::os::raw::c_char,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_number_ex(
        ctx: *mut mu_Context,
        value: *mut mu_Real,
        step: mu_Real,
        fmt: *const ::std::os::raw::c_char,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_header_ex(
        ctx: *mut mu_Context,
        label: *const ::std::os::raw::c_char,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_begin_treenode_ex(
        ctx: *mut mu_Context,
        label: *const ::std::os::raw::c_char,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_end_treenode(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_begin_window_ex(
        ctx: *mut mu_Context,
        title: *const ::std::os::raw::c_char,
        rect: mu_Rect,
        opt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_end_window(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_open_popup(ctx: *mut mu_Context, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn mu_begin_popup(
        ctx: *mut mu_Context,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn mu_end_popup(ctx: *mut mu_Context);
}
unsafe extern "C" {
    pub fn mu_begin_panel_ex(
        ctx: *mut mu_Context,
        name: *const ::std::os::raw::c_char,
        opt: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn mu_end_panel(ctx: *mut mu_Context);
}
