[package]
name = "brickworks"
edition = "2021"
version = "0.0.1"
license = "MIT"
description = "Brick Rigs mod loader"
repository = "https://github.com/KoT3isGood/brickrust"
publish = true

[dependencies]
libloading = "0.9"
brickrust_macros = { version = "0.0.1", path = "../macros" }
min_hook_rs = "2.2.1"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-gnu"]
default-target = "x86_64-pc-windows-gnu"
