[package]
name = "brickworks_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
brickworks = {version = "0.1.0", path = "../brickworks"}
brickrust_macros = { version = "0.0.2", path = "../macros" }
libloading = "0.9"
min_hook_rs = "2.2.1"
inventory = "0.3.24"

[lib]
name = "brickworks"
crate-type = ["cdylib"]

[features]
default=[]
brmk=[]
impl=[]

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-gnu"]
default-target = "x86_64-pc-windows-gnu"
