[package]
name = "brickrust_macros"
edition = "2021"
version = "0.0.1"
license = "MIT"
description = "Macros for brickrust"
repository = "https://github.com/KoT3isGood/brickrust"
publish = true

[lib]
name = "brickrust_macros"
proc-macro=true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-gnu"]
default-target = "x86_64-pc-windows-gnu"
