#![allow(nonstandard_style)]
use crate::ue::coreuobject::*;
use crate::ue::fstring::*;

#[repr(C)]
#[derive(Debug)]
pub struct AActor
{
    pub uobject: UObject 

}
#[repr(C)]
#[derive(Debug)]
pub struct AActorVTable
{
    pub uobject: UObjectVTable,
    pub OnRep_ReplicateMovement: unsafe extern "C" fn( act: *mut AActor ),
    pub TearOff: unsafe extern "C" fn( act: *mut AActor ),
    pub HasNetOwner: unsafe extern "C" fn( act: *mut AActor ),
    pub HasLocalNetOwner: unsafe extern "C" fn( act: *mut AActor ),
    pub OnRep_Owner: unsafe extern "C" fn( act: *mut AActor ),
    pub SetReplicateMovement: unsafe extern "C" fn( act: *mut AActor ),
    pub OnRep_AttachmentReplication: unsafe extern "C" fn( act: *mut AActor ),
    pub IsReplicationPausedForConnection: unsafe extern "C" fn( act: *mut AActor ),
    pub OnReplicationPausedChanged: unsafe extern "C" fn( act: *mut AActor ),
    pub ReplicateSubobjects: unsafe extern "C" fn( act: *mut AActor ),
    pub OnSubobjectCreatedFromReplication: unsafe extern "C" fn( act: *mut AActor ),
    pub OnSubobjectDestroyFromReplication: unsafe extern "C" fn( act: *mut AActor ),
    pub PreReplication: unsafe extern "C" fn( act: *mut AActor ),
    pub PreReplicationForReplay: unsafe extern "C" fn( act: *mut AActor ),
    pub RewindForReplay: unsafe extern "C" fn( act: *mut AActor ),
    pub OnRep_Instigator: unsafe extern "C" fn( act: *mut AActor ),
    pub EnableInput: unsafe extern "C" fn( act: *mut AActor ),
    pub DisableInput: unsafe extern "C" fn( act: *mut AActor ),
    pub GetVelocity: unsafe extern "C" fn( act: *mut AActor ),
    pub SetActorHiddenInGame: unsafe extern "C" fn( act: *mut AActor ),
    pub K2_DestroyActor: unsafe extern "C" fn( act: *mut AActor ),
    pub AddTickPrerequisiteActor: unsafe extern "C" fn( act: *mut AActor ),
    pub AddTickPrerequisiteComponent: unsafe extern "C" fn( act: *mut AActor ),
    pub RemoveTickPrerequisiteActor: unsafe extern "C" fn( act: *mut AActor ),
    pub RemoveTickPrerequisiteComponent: unsafe extern "C" fn( act: *mut AActor ),
    pub BeginPlay: unsafe extern "C" fn( act: *mut AActor ),
    pub EndPlay: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorBeginOverlap: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorEndOverlap: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorBeginCursorOver: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorEndCursorOver: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnClicked: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnReleased: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnInputTouchBegin: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnInputTouchEnd: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnInputTouchEnter: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyActorOnInputTouchLeave: unsafe extern "C" fn( act: *mut AActor ),
    pub NotifyHit: unsafe extern "C" fn( act: *mut AActor ),
    pub SetLifeSpan: unsafe extern "C" fn( act: *mut AActor ),
    pub GetLifeSpan: unsafe extern "C" fn( act: *mut AActor ),
    pub GatherCurrentMovement: unsafe extern "C" fn( act: *mut AActor ),
    pub GetDefaultAttachComponent: unsafe extern "C" fn( act: *mut AActor ),
    pub ApplyWorldOffset: unsafe extern "C" fn( act: *mut AActor ),
    pub IsLevelBoundsRelevant: unsafe extern "C" fn( act: *mut AActor ),
    pub GetNetPriority: unsafe extern "C" fn( act: *mut AActor ),
    pub GetReplayPriority: unsafe extern "C" fn( act: *mut AActor ),
    pub GetNetDormancy: unsafe extern "C" fn( act: *mut AActor ),
    pub OnActorChannelOpen: unsafe extern "C" fn( act: *mut AActor ),
    pub UseShortConnectTimeout: unsafe extern "C" fn( act: *mut AActor ),
    pub OnSerializeNewActor: unsafe extern "C" fn( act: *mut AActor ),
    pub OnNetCleanup: unsafe extern "C" fn( act: *mut AActor ),
    pub TickActor: unsafe extern "C" fn( act: *mut AActor ),
    pub PostActorCreated: unsafe extern "C" fn( act: *mut AActor ),
    pub LifeSpanExpired: unsafe extern "C" fn( act: *mut AActor ),
    pub PostNetReceiveRole: unsafe extern "C" fn( act: *mut AActor ),
    pub PostNetInit: unsafe extern "C" fn( act: *mut AActor ),
    pub _a0: unsafe extern "C" fn( act: *mut AActor ),
    pub OnRep_ReplicatedMovement: unsafe extern "C" fn( act: *mut AActor ),
    pub PostNetReceiveLocationAndRotation: unsafe extern "C" fn( act: *mut AActor ),
    pub PostNetReceiveVelocity: unsafe extern "C" fn( act: *mut AActor ),
    pub PostNetReceivePhysicState: unsafe extern "C" fn( act: *mut AActor ),
    pub SetOwner: unsafe extern "C" fn( act: *mut AActor ),
    pub CheckStillInWorld: unsafe extern "C" fn( act: *mut AActor ),
    pub Tick: unsafe extern "C" fn( act: *mut AActor ),
    pub ShouldTickIfViewportsOnly: unsafe extern "C" fn( act: *mut AActor ),
    pub IsNetRelevantFor: unsafe extern "C" fn( act: *mut AActor ),
    pub IsReplayRelevantFor: unsafe extern "C" fn( act: *mut AActor ),
    pub IsRelevancyOwnerFor: unsafe extern "C" fn( act: *mut AActor ),
    pub PreInitializeComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub PostInitializeComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub DispatchPhysicsCollisionHit: unsafe extern "C" fn( act: *mut AActor ),
    pub GetNetOwner: unsafe extern "C" fn( act: *mut AActor ),
    pub GetNetOwningPlayer: unsafe extern "C" fn( act: *mut AActor ),
    pub GetNetConnection: unsafe extern "C" fn( act: *mut AActor ),
    pub DestroyNetworkActorHandled: unsafe extern "C" fn( act: *mut AActor ),
    pub RegisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub PreRegisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub PostRegisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub UnregisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub PostUnregisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub ReregisterAllComponents: unsafe extern "C" fn( act: *mut AActor ),
    pub MarkComponentsAsPendingKill: unsafe extern "C" fn( act: *mut AActor ),
    pub InvalidateLightingCacheDetailed: unsafe extern "C" fn( act: *mut AActor ),
    pub TeleportTo: unsafe extern "C" fn( act: *mut AActor ),
    pub TeleportSucceeded: unsafe extern "C" fn( act: *mut AActor ),
    pub ClearCrossLevelReferences: unsafe extern "C" fn( act: *mut AActor ),
    pub IsBasedOnActor: unsafe extern "C" fn( act: *mut AActor ),
    pub IsAttachedTo: unsafe extern "C" fn( act: *mut AActor ),
    pub RerunConstructionScripts: unsafe extern "C" fn( act: *mut AActor ),
    pub OnConstruction: unsafe extern "C" fn( act: *mut AActor ),
    pub RegisterActorTickFunctions: unsafe extern "C" fn( act: *mut AActor ),
    pub Destroyed: unsafe extern "C" fn( act: *mut AActor ),
    pub FellOutOfWorld: unsafe extern "C" fn( act: *mut AActor ),
    pub OutsideWorldBounds: unsafe extern "C" fn( act: *mut AActor ),
    pub GetComponentsBoundingBox: unsafe extern "C" fn( act: *mut AActor ),
    pub CalculateComponentsBoundingBoxInLocalSpace: unsafe extern "C" fn( act: *mut AActor ),
    pub GetComponentsBoundingCylinder: unsafe extern "C" fn( act: *mut AActor ),
    pub GetSimpleCollisionCylinder: unsafe extern "C" fn( act: *mut AActor ),
    pub IsRootComponentCollisionRegistered: unsafe extern "C" fn( act: *mut AActor ),
    pub TornOff: unsafe extern "C" fn( act: *mut AActor ),
    pub GetComponentsCollisionResponseToChannel: unsafe extern "C" fn( act: *mut AActor ),
    pub CanBeBaseForCharacter: unsafe extern "C" fn( act: *mut AActor ),
    pub TakeDamage: unsafe extern "C" fn( act: *mut AActor ),
    pub InternalTakeRadialDamage: unsafe extern "C" fn( act: *mut AActor ),
    pub InternalTakePointDamage: unsafe extern "C" fn( act: *mut AActor ),
    pub BecomeViewTarget: unsafe extern "C" fn( act: *mut AActor ),
    pub EndViewTarget: unsafe extern "C" fn( act: *mut AActor ),
    pub CalcCamera: unsafe extern "C" fn( act: *mut AActor ),
    pub HasActiveCameraComponent: unsafe extern "C" fn( act: *mut AActor ),
    pub HasActivePawnControlCameraComponent: unsafe extern "C" fn( act: *mut AActor ),
    pub GetHumanReadableName: unsafe extern "C" fn( act: *mut AActor ) -> FString,
    pub Reset: unsafe extern "C" fn( act: *mut AActor ),
    pub GetLastRenderTime: unsafe extern "C" fn( act: *mut AActor ),
    pub ForceNetRelevant: unsafe extern "C" fn( act: *mut AActor ),
    pub ForceNetUpdate: unsafe extern "C" fn( act: *mut AActor ),
    pub PrestreamTextures: unsafe extern "C" fn( act: *mut AActor ),
    pub GetActorEyesViewPoint: unsafe extern "C" fn( act: *mut AActor ),
    pub GetTargetLocation: unsafe extern "C" fn( act: *mut AActor ),
    pub PostRenderFor: unsafe extern "C" fn( act: *mut AActor ),
    pub FindComponentByClass: unsafe extern "C" fn( act: *mut AActor ),
    pub IsComponentRelevantForNavigation: unsafe extern "C" fn( act: *mut AActor ),
    pub DisplayDebug: unsafe extern "C" fn( act: *mut AActor ),
    pub _a1: unsafe extern "C" fn( act: *mut AActor ),
}
